### ISSUE TITLE
Resetting all Quests/Storylines

### ISSUE THREAD

**Issue by iChasm03** [FrinshHD/AnturniaQuests#12]
The ability to use 
/quests storylines reset <player> all
/quests reset <player> all
So then you can reset all quests/storylines instead of having to specify each quest individually.

**Comment by FrinshHD** [comment]
Planed features:
- `/quests reset <playerName>`
- confirm reseting all quests for a player by typing the command again in the next 10 seconds

**Comment by FrinshHD** [comment]
https://logic-jenkins.anturnia.net/job/AnturniaQuests/61/artifact/target/AnturniaQuests-1.0.3.61.jar
