### ISSUE TITLE
Tab Commands

### ISSUE THREAD

**Issue by iChasm03** [FrinshHD/AnturniaQuests#7]
The ability to tab in different commands, mainly for resetting storylines and quests so you don't have to fully type out the player name and/or the quest/storyline name.

**Comment by FrinshHD** [comment]
![Image](https://github.com/FrinshHD/AnturniaQuests/assets/62144694/39f11746-5786-494c-89ae-8994c3320b26)

**Comment by FrinshHD** [comment]
![Image](https://github.com/FrinshHD/AnturniaQuests/assets/62144694/8ca90fa8-9723-419d-aa88-88c0b8dcf1d9)
